version: "3"
services:
  backend:
    restart: always
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 5000
    volumes:
      - ./server:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
